### ISSUE TITLE
Course Validation Error Message Inconsistency Bug

### ISSUE THREAD

**Issue by Davidster** [stumash/CoursePlanner#12]
## The Bug:

 It is possible to trigger two sequences which, when validated, provide conflicting error messages. 
One message indicates a prereq relation between courses, and another indicates a coreq relation between courses. As per the true data, it is a prereq relation.

## To Reproduce:

1. Open up a fresh sequence, and drag COMP 249 into SUMMER 1. You will notice that COMP 249 is a prerequisite for COMP 352 so you get the correct error message: **COMP 249 must be taken before COMP 352**

![image](https://cloud.githubusercontent.com/assets/2389735/22573494/3c81a8be-e977-11e6-898a-fe83c77237e5.png)

2. Open up a new fresh sequence, and drag COMP 232 into WINTER 2. The result:

![image](https://cloud.githubusercontent.com/assets/2389735/22573304/5812f0b6-e976-11e6-9e60-b33a1d1fbe27.png)

As you can see, the message for the COMP 249 conflict now reads: **COMP 249 must be taken at least as soon as COMP 352**, which is the message that we provide when a corequisite relationship is not satisfied.

**Comment by stumash** [comment]
I'm closing this since the validator needs a complete rewrite

**Comment by Davidster** [comment]
Note that this issue may come back to haunt us unless of course you have a solution which takes care of it already in mind.

**Comment by stumash** [comment]
Noted
