### ISSUE TITLE
Course Validation Bug From Moving Work Term to Different Semester

### ISSUE THREAD

**Issue by stumash** [stumash/CoursePlanner#13]
# Problem Description:
If you drag and drop and work term into another semester, all the courses in that semester get dropped from the data that's sent to the SequenceValidator on the server-side.  So, any later classes which rely on those courses as prereqs complain that their prereqs are not being taken early enough.
### Possible fixes:
*   Moving a work term from semester b to semester a results in a "shuffling-down" of all courses in semester a or later by one semester.  After this shifting over of one semester, the data is sent to the server for sequence validation.
*   Other ideas?

**Comment by PeterGhimself** [comment]
I see that David tried to handle this issue, now I was just playing around with the site and noticed that "work semester" course divs aren't draggable, I guess that's fine but when you add a course to a work semester it seems to just delete that work semester from existence.
You can eliminate them all if you just keep dragging courses into terms with "work semester" course divs in them. 

Maybe we should add a UI widget/area for creating course divs? We could create some templates and load them up based on the users choice, such as (obviously) a work semester, or maybe even electives.

**Comment by stumash** [comment]
I'm closing this since the validator needs a complete rewrite, more or less
