### ISSUE TITLE
Add feedback dialog box

### ISSUE THREAD

**Issue by Davidster** [stumash/CoursePlanner#133]
Add a dialog box that pops up when you click a [feedback icon](https://material.io/icons/#ic_feedback) on the top right of the page. The box should contain an input field with a maximum character count of 1000 and could include a character counter. The feedback submitted should be sent to us somehow.. maybe email concordiacourseplanner@gmail.com.

**Comment by Davidster** [comment]
Backend dependency development started on branch [addEmailServlet-133](/stumash/CoursePlanner/tree/addEmailServlet-133)

**Comment by PeterGhimself** [comment]
front end development started on branch [addFeedbackDialogBox-133](/stumash/CoursePlanner/tree/addFeedbackDialogBox-133)
