### ISSUE TITLE
Missing AERO for recommended sequence options

### ISSUE THREAD

**Issue by PeterGhimself** [stumash/CoursePlanner#143]
We already have the AERO course info in our DB, but not the recommended sequences for AERO.

Data for recommended sequence should be scraped from:
https://www.concordia.ca/encs/students/sas/undergrad-program-info/course-sequences/aerospace.html

**Comment by Davidster** [comment]
development start on branch [addAeroSupport-143](/stumash/CoursePlanner/tree/addAeroSupport-143)
