### ISSUE TITLE
Minor issue with course data scraper

### ISSUE THREAD

**Issue by Davidster** [stumash/CoursePlanner#31]
If you try to run the course data scraper (`Rscript scrape-course-data.r`) without first creating the folder `course-info-jsonfiles/`, the script will encounter the following error:

```shell
Error in writeLines(prettify(toJSON(full.course.strings)), file.connection) :
  cannot open the connection
In addition: Warning message:
In writeLines(prettify(toJSON(full.course.strings)), file.connection) :
  cannot open file 'course-info-jsonfiles/ENCS_full-course-info.json': No such file or directory
Execution halted
```

Suggested fix: the script should create the folder before trying to put files into it.

**Comment by stumash** [comment]
started development on branch [enhancement-31](https://github.com/stumash/CoursePlanner/tree/enhancement-31)

**Comment by stumash** [comment]
yes I know we are struggling with a naming convention here
