### ISSUE TITLE
Add new detail to sequence json data

### ISSUE THREAD

**Issue by Davidster** [stumash/CoursePlanner#32]
## Explanation

The sequences presented on Concordia's website sometimes include entries where the student is allowed to choose any courses from a given list (course a or course b or course c etc.). The sequence json spec needs to be enhanced to support this and in the future the front-end app will also need to account for this case with a UI element. 

## Example

The following screenshot was taken from following website: https://www.concordia.ca/encs/computer-science-software-engineering/students/course-sequences/sept-soen-real-time.html

![image](https://user-images.githubusercontent.com/2389735/27256657-cb734668-538a-11e7-8936-0d524b176a70.png)

Here is how our site currently reacts to this:

![image](https://user-images.githubusercontent.com/2389735/27256647-67fb3b7c-538a-11e7-8b04-a04a5224f4ed.png)

**Comment by Davidster** [comment]
working on branch `improveSequenceJsonSpec`

**Comment by PeterGhimself** [comment]
Is that the correct syntax for linking your branch?
Stu did it like for his
```development starting on branch [feature_mutiple-dev-environments-29](/stumash/CoursePlanner/tree/feature_multiple-dev-environments-29)```

**Comment by Davidster** [comment]
updated
