### ISSUE TITLE
Very weird style for MECH/INDU recommended sequences

### ISSUE THREAD

**Issue by Davidster** [stumash/CoursePlanner#39]
I want your guys opinion on what the resulting JSON should look for the following:

([INDU-Coop](https://www.concordia.ca/encs/mechanical-industrial/students/undergraduate/course-sequences/co-op-indu.html))
![image](https://user-images.githubusercontent.com/2389735/27979916-8e778fa4-6347-11e7-90dd-d789b7264ea3.png)

In english words, this page is saying that 

- you must take `INDU 421` and `INDU 423` in the fall of year 4
- you must take `INDU 321` and `INDU 342` in the winter of year 4
- you must take 17.75 credits of technical electives between fall & winter of year 4
- you must take the course `INDU 490` in BOTH the fall and winter of year 4

It may be worth noting that there are other sequences that include a course that spans over two semesters like `INDU 490` does, in which case the current scraper plainly adds this course to both of the two semesters in question (the website also lists the course in both the semesters instead of this stupidity of putting ANDs and ORs in the semester season header)

To re-iterate, I want to know what you guys think the resulting json should look like for these fall and winter semesters. Currently, the scraper poops the bed and does something like this:

```json
{
    "season": "fall",
    "courseList": [
        {
            "code": "INDU 421",
            "isElective": "false",
            "electiveType": ""
        },
        {
            "code": "INDU 423",
            "isElective": "false",
            "electiveType": ""
        }
    ],
    "isWorkTerm": "false"
},
{
    "season": "winter",
    "courseList": [
        {
            "code": "INDU 321",
            "isElective": "false",
            "electiveType": ""
        },
        {
            "code": "INDU 342",
            "isElective": "false",
            "electiveType": ""
        }
    ],
    "isWorkTerm": "false"
},
{
    "season": "fall",
    "courseList": [
        {
            "code": "INDU 490",
            "isElective": "false",
            "electiveType": ""
        }
    ],
    "isWorkTerm": "false"
}
```

**Comment by PeterGhimself** [comment]
couldn't we account for this by making it a special case during scraping, when coming across INDU?

**Comment by Davidster** [comment]
yea sure that's not problem, but like I said, what should the resulting JSON look like?

**Comment by Davidster** [comment]
I have a proposal: 

```json
{
    "season": "fall",
    "courseList": [
        {
            "code": "INDU 421",
            "isElective": "false",
            "electiveType": ""
        },
        {
            "code": "INDU 423",
            "isElective": "false",
            "electiveType": ""
        },
        {
            "code": "INDU 490",
            "isElective": "false",
            "electiveType": ""
        },
        {
            "code": "",
            "isElective": "true",
            "electiveType": "Program"
        },
        {
            "code": "",
            "isElective": "true",
            "electiveType": "Program"
        },
        {
            "code": "",
            "isElective": "true",
            "electiveType": "Program"
        }
    ],
    "isWorkTerm": "false"
},
{
    "season": "winter",
    "courseList": [
        {
            "code": "INDU 321",
            "isElective": "false",
            "electiveType": ""
        },
        {
            "code": "INDU 342",
            "isElective": "false",
            "electiveType": ""
        },
        {
            "code": "INDU 490",
            "isElective": "false",
            "electiveType": ""
        },
        {
            "code": "",
            "isElective": "true",
            "electiveType": "Program"
        },
        {
            "code": "",
            "isElective": "true",
            "electiveType": "Program"
        },
        {
            "code": "",
            "isElective": "true",
            "electiveType": "Program"
        }
    ],
    "isWorkTerm": "false"
}
```

**Comment by PeterGhimself** [comment]
Why don't we account for this all with one single `semesterContainer` element which will have the header (in this case) `{YEAR 4 - FALL AND WINTER}` and then just put a course object for technical elective (17.5 creds) and put `INDU 490` in there too. Any extra information that is necessary we can display in the info box under `NOTE` section or the (to be implemented) `DESCRIPTION` section.
Would it be possible to have a semester object with `"season": "fall, winter"` or something like that?

**Comment by Davidster** [comment]
I don't think we should change the format of our sequence json data just to account for this one exceptional case. I was more looking for what this could/should look like within the limits of our current json format (i.e. Not having more than one season per semester object)
