### ISSUE TITLE
Add ability to validate the total credits of a given sequence

### ISSUE THREAD

**Issue by Davidster** [stumash/CoursePlanner#40]
In addition to making sure prerequisite and corequisite relationships are respected, we want to make sure that the minimum number of credits defined for the users program of study is met. For example, in engineering you need to do 120 credits and in computer science u only need to do 90 credits

**Comment by Davidster** [comment]
hi

**Comment by Davidster** [comment]
work started on branch [addMinTotalCredits](/stumash/CoursePlanner/tree/addMinTotalCredits)

**Comment by stumash** [comment]
so what's the deal with this issue? is it for frontend or backend?

**Comment by Davidster** [comment]
This is backend. As per our schema defined in `recommendedSequence.json`, sequences have a required property `minTotalCredits` which will end up making its way to the server during a sequence validation request. So ya you're gunna wanna add a clause to the backend which reads its value and validates against it.
