### ISSUE TITLE
MinCredits undefined

### ISSUE THREAD

**Issue by PeterGhimself** [stumash/CoursePlanner#48]
Here is what it looks like when we load up a sequence, such as _SOEN-General-Coop.json_:
![image](https://user-images.githubusercontent.com/19865282/28243209-d516a244-698f-11e7-9de6-6fead08f974a.png)

This functionality should be working for the MVP.

Additionally, the Program name in the _sequenceBuilder_ page and in the _splash_ page select options should not contain ".json" in the their names
![image](https://user-images.githubusercontent.com/19865282/28243149-fa40a5c6-698d-11e7-9643-a2c3f4e9e985.png)

**Comment by Davidster** [comment]
how do I reproduce this error? when I pick BLDG-Coop I see this: 

![image](https://user-images.githubusercontent.com/2389735/28288261-ad819b2a-6b0c-11e7-940d-ee54a16510eb.png)

**Comment by stumash** [comment]
I am going to close this due to the frontend rewrite.  Cool with everyone?

**Comment by PeterGhimself** [comment]
Go ahead

**Comment by PeterGhimself** [comment]
actually I'll just close it
