### ISSUE TITLE
Deploy success message broken

### ISSUE THREAD

**Issue by Davidster** [stumash/CoursePlanner#51]
If there are errors in the building of the frontend components (babel, browserify, etc), the deploy script claims to have succeeded and proceeds to transfer courseplanner.war to the VM. This should not be the case

**Comment by PeterGhimself** [comment]
There were already enough errors in the success message as it was before the 10 extra added npm dependencies for react... such as if you wait long enough to put your password in when prompted (say one minute), and then the connection actually breaks and you do not deploy but it still says "deployed successfully at ____". One of the few bugs that I've noticed already...

**Comment by Davidster** [comment]
Alright well let's make sure the success message is airtight before closing this issue

**Comment by stumash** [comment]
development started on branch [deployScriptFix-51-60](/stumash/CoursePlanner/tree/deployScriptFix-51-60)
