### ISSUE TITLE
Deploy prod version of react with prod version of project and vice versa

### ISSUE THREAD

**Issue by Davidster** [stumash/CoursePlanner#60]
Instead of using `x` as a param for `deploy.sh`, simply build the frontend with a development version of react for our personal war files (`courseplanner{d,s,p,j,m}`) and with a production version of react when were pushing to prod (`courseplanner`).

**Comment by stumash** [comment]
I don't get what you mean by personal environment

**Comment by Davidster** [comment]
I dont get what you mean by 🌑

**Comment by stumash** [comment]
wut

**Comment by stumash** [comment]
the deploy command will be used as follows:
* `./deploy.sh {name}` to deploy personal war file with dev version of react.
* `./deploy.sh prod` to deploy prod war file with prod version of react.

**Comment by stumash** [comment]
development started on branch [deployScriptFix-51-60](/stumash/CoursePlanner/tree/deployScriptFix-51-60)
