### ISSUE TITLE
Create well-defined json data specification and derive validation logic from it

### ISSUE THREAD

**Issue by Davidster** [stumash/CoursePlanner#67]
## The Problem

Currently, we are discussing the format of our json data through conversations and then our webscraping and data validation code reflects this format we have in our heads of what the data needs to look like. 

![image](https://user-images.githubusercontent.com/2389735/28858210-fe5c6374-771c-11e7-8930-2fd28496299c.png)

### It would be much better if we had both:
1. A well-defined set of files describing the format of all json data stored in the DB
2. A system for validating said data which is derived from our specifications rather than manually writing the validation code each time the spec changes.

## A Proposed Solution

To solve the first issue from above, we can define our data using the [json schema](http://json-schema.org/) specification. This will allow us to create files which define the constraints of our json data member(s). The newest revision of `json schema` is called draft-06. We should use it.

To solve the second issue from above, we can use one of many [npm modules](http://json-schema.org/implementations.html#validators) to check all of our scraped data before inserting it into the DB. If all goes well, very little code will have to be written for this step as the validation logic will be derived from our declared spec. Based on this [benchmark](https://github.com/ebdrup/json-schema-benchmark) along with the popularity of the repository and frankly the length of its README, it seems that the module [ajv](https://github.com/epoberezkin/ajv) is our best option

**Comment by stumash** [comment]
yeeee buddy

**Comment by Davidster** [comment]
Development started on branch [implementJsonSchema-67](/stumash/CoursePlanner/tree/implementJsonSchema-67)
