### ISSUE TITLE
Add program info panel

### ISSUE THREAD

**Issue by PeterGhimself** [stumash/CoursePlanner#73]
Should contain the formal title of the program, total min credits, and the URL that was used to scrape the data for that program.

**Comment by Davidster** [comment]
Let's place it on top of the semester table/list and format it as the program title with (# Credits) at the end and have be a hyperlink to the URL. I'll make the necessary changes to the `reccomendedSequence.json` spec to include a new property: `formalTitle`

**Comment by Davidster** [comment]
Development completed on branch [addSequenceFormalTitle-73](/stumash/CoursePlanner/tree/addSequenceFormalTitle-73)

**Comment by Davidster** [comment]
In the end, I removed the `prettyName` property from the sequence data and replaced it with `sequenceInfo` instead. See ab4f3f413b637586f547246f4c39e165a5166fbd for more details.
