### ISSUE TITLE
weird course info json for lab hours and lecture hours

### ISSUE THREAD

**Issue by stumash** [stumash/CoursePlanner#81]
![image](https://user-images.githubusercontent.com/13181078/29099710-0ab03eea-7c75-11e7-8cc6-3f9dc572540c.png)

As you can see, the course info JSON for SOEN 423 (let's call the JSON object `obj`) contains both `obj["lab"]["hours"] = "two hours per week"` and `obj["labHours"] = "two hours per week"`.  Same is true from `lectureHours`.

This is clearly wrong.

The JSON output of the `r` scraper when ran on my personal machine does not contain these incorrect redundancies.  I suspect that this is "feature" of MongoDB where it avoids entirely replacing old data with new data and instead just tries to add the difference between the old and new versions of data when possible.

**Comment by Davidster** [comment]
This is very confusing. I noticed this issue as well and dropped the course info database for dev and prod then reran the scraper and issues seemed to have been resolved. It must be that the old scraper has been run again

**Comment by Davidster** [comment]
Misclick

**Comment by Davidster** [comment]
I just cleared the DB and re-ran the webscraper and it's all good now

**Comment by Davidster** [comment]
Do we want to try to fix the fact that properties end up getting duplicated when they're renamed? I think it's a non-issue any nothing needs to be changed. If there are no objections I will close this issue.

**Comment by PeterGhimself** [comment]
It can't hurt to clean up the JSON, we might as well do it.

**Comment by Davidster** [comment]
The json is already clean

**Comment by Davidster** [comment]
as per my comment above: "I just cleared the DB and re-ran the webscraper and it's all good now"

**Comment by PeterGhimself** [comment]
Yes I saw that, however the first sentence of your next comment thereafter confused me and made it seem like there is still this issue of redundancy. 
"Do we want to try to fix `the fact that properties end up getting duplicated when they're renamed`?" makes it sound like there's still a problem.

**Comment by Davidster** [comment]
yes, the problem is that when you rename or remove a property from the json spec and then store the new data to the DB, the old property will remain as the DB write merges what's currently contained in the DB with what's currently being added. This means that the old property ends up lingering. The workaround is to simply clear the DB and re-run the scraper so the old property actually gets removed. Due to the existence of this workaround and the fact that we aren't going to be updating the json spec often in the long run, I see this as a non-issue.

**Comment by stumash** [comment]
I also see it as a non-issue. It's probably good that the dp has an 'add-only' by default behaviour on `insert`.  Clearing and then inserting seems like a logical way to handle it.
