### ISSUE TITLE
course info scraper bugs

### ISSUE THREAD

**Issue by stumash** [stumash/CoursePlanner#84]
the course info scraper is currently failing on certain courses on certain webpages. Looks like those regex need some tweaking... I'm on it.

**Comment by stumash** [comment]
development started on branch [fixCourseInfoScraper-84](/stumash/CoursePlanner/tree/fixCourseInfoScraper-84)

**Comment by Davidster** [comment]
10/10 issue description

**Comment by stumash** [comment]
certain courses don't have required properties, i.e. `credits`, `desription`

**Comment by stumash** [comment]
some `description` properties contain the contents of what should be scraped into the separate `NOTE` property.  working on that now.
