### ISSUE TITLE
Courses missing from recommended sequences

### ISSUE THREAD

**Issue by Davidster** [stumash/CoursePlanner#86]
If you go through the recommended sequences, you'll quickly realise that some courses are missing, such as `CART 351`, `FFAR 250`, `ENGR 418`, `MECH 490` just to name a few. 

I think it's obvious that we should at the least have all courses from the recommended sequences in our course info DB.

I'll probably write a node program which we can use temporarily to list all courses contained in the recommended sequences collection that are not contained in our course info collection. Then we can locate them on the undergraduate calendar and append items to `course-info-data-sources.txt` accordingly.

Thoughts?

**Comment by stumash** [comment]
The current data sources that we're scraping from are just straight-up missing those courses.  I don't know why on earth Concordia's page of all ENGR courses would not also have the courses ENGR 418, 490, but it doesn't.  We need other data sources.  If you want to do that in node, I don't have a problem with it.  However if these data sources aren't somehow uniform in their format/html structure, then we may need to consider alternate scraping strategies in general, i.e. making many page-specific scrapers and giving up on generalizability.

**Comment by Davidster** [comment]
Well isn't that wonderful 👿

**Comment by Davidster** [comment]
If this is too time consuming to solve by updating the webscraper, we could always manually enter the courses into the DB. Maybe we could make a tiny DB-admin frontend that we can use to manually add in courses on the fly. Could be very useful down the line if many users are failing to find a certain course which is listed in an obscure part of Concordias site. Thoughts?

**Comment by Davidster** [comment]
I'm going to add a folder to `webscraping/courseInfo` called `manualEntry` which will contain json file(s) with courses which we want to add to the DB manually. I think it makes sense to keep this file in the repository since it's small and unlikely to grow in size over time. I'll add a section to the storer which validates and inserts these courses in the same way that the scraped courses are handled. Any objections?

**Comment by stumash** [comment]
I guess it's cool. I feel like the directory should be called 'dataToStore' instead of 'scrapedJson' so that it can contain two files  called 'scrapedData' and 'manualEntey'. Dunno what do u think?

**Comment by Davidster** [comment]
We will place a file called `manualEntry.json` into `webscraping/storing/` which will be an array of course info objects that are too much trouble to scrape.

**Comment by Davidster** [comment]
Development on the topic of the above comment started on branch [addDBManualEntry-86](/stumash/CoursePlanner/tree/addDBManualEntry-86)
