### ISSUE TITLE
complete redo of sequence validation

### ISSUE THREAD

**Issue by stumash** [stumash/CoursePlanner#95]
Ever since we redid our frontend in React and updated our scraper/data format, we've been badly itching for a fresh version of our sequence validation.  As we discussed in person, there's a O(n) algorithm for this and it'll be put to use.

**Comment by Davidster** [comment]
Closing issues #40 and #72 is a corequisite for closing this issue.

**Comment by stumash** [comment]
development started on branch [newSequenceValidation-95](/stumash/CoursePlanner/tree/newSequenceValidation-95)

**Comment by Davidster** [comment]
Made u a little helper function to test the validation. Stick this snippet into the `componentDidUpdate()` function of `mainPage.js` and each time the course sequence changes, the site will send a validation request and log the request/response data:

```javascript
if(!this.state.courseSequenceObject.isLoading && !_.isEqual(prevState.courseSequenceObject.yearList, this.state.courseSequenceObject.yearList)){
    console.group("Year list changed - sending new sequence to server: ");
    console.log("courseSequenceObject:\n", this.state.courseSequenceObject);
    $.ajax({
        type: "POST",
        url: "api/validate",
        data: JSON.stringify({"courseSequenceObject" : this.state.courseSequenceObject}),
        success: (response) => {
            console.log("server response:\n", JSON.parse(response));
            console.groupEnd();
        }
    });
}
```
