### ISSUE TITLE
Add touch support to drag n drop

### ISSUE THREAD

**Issue by Davidster** [stumash/CoursePlanner#99]
In order to support drag n drop for mobile devices which use touch screens as opposed to mouse/cursors, we must swap the "backend" that we pass to `react-dnd`.

Currently we are using [react-dnd-html5-backend](https://github.com/react-dnd/react-dnd-html5-backend) which does not have touch screen support. So we shall switch to using [react-dnd-touch-backend](https://github.com/yahoo/react-dnd-touch-backend).

To accomplish this, we need to add `react-dnd-touch-backend` to our dependencies:

`npm install --save react-dnd-touch-backend`

then we just need to replace the HTML5Backend with the touch version and make sure to enable the `enableMouseEvents` property

**Comment by PeterGhimself** [comment]
Sounds pretty straight forward... besides that there's nothing else to do for this issue?

**Comment by Davidster** [comment]
As long as drag and drop works on both touch devices and mouse devices then the issue is solved. Verifying full support for computers which use both a mouse a touch screen is a plus (I'm pretty sure this backend works for that purpose).
